/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import smartretailer.Invoice;
import controllers.ServerController;
import controllers.WebServiceController;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Oshan
 */
public class CreateRecept extends javax.swing.JDialog {

    /**
     * Creates new form CreateRecept
     */
    static DecimalFormat df2 = new DecimalFormat("#,###,###,##0.00");
    private static int invoiceId;
    private static Double GTotal;

    boolean pressed = false;

    public CreateRecept(java.awt.Frame parent, boolean modal, int invoiceId, Double GTotal) {
        super(parent, modal);
        initComponents();
        CreateRecept.invoiceId = invoiceId;
        CreateRecept.GTotal = GTotal;

        int invoiceViewNumber = invoiceId + 10000;

        GrandTotalLbl.setText("Rs. "+df2.format(GTotal));
        InvoiceNumberLbl.setText("Invoice Number: "+invoiceViewNumber);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReceptTypeBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        InvoiceNumberLbl = new javax.swing.JLabel();
        GenarateReceptBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        GrandTotalLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CashRadioBtn = new javax.swing.JRadioButton();
        OnlineTransferRadioBtn = new javax.swing.JRadioButton();
        BankRadioBtn = new javax.swing.JRadioButton();
        ChequeRadioBtn = new javax.swing.JRadioButton();
        VisaRadioBtn = new javax.swing.JRadioButton();
        MasterRadioBtn = new javax.swing.JRadioButton();
        AmexRadioBtn = new javax.swing.JRadioButton();
        CreditRadioBtn = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NoteLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReceptNote = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Genarate Receipt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        InvoiceNumberLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        InvoiceNumberLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InvoiceNumberLbl.setText("INVOICE NO : ");

        GenarateReceptBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        GenarateReceptBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        GenarateReceptBtn.setText("Genarate");
        GenarateReceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenarateReceptBtnMouseClicked(evt);
            }
        });
        GenarateReceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenarateReceptBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setText("Grand Total");

        GrandTotalLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        GrandTotalLbl.setText("Rs. 0.00");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("Select Payment Method");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        CashRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(CashRadioBtn);
        CashRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        CashRadioBtn.setSelected(true);
        CashRadioBtn.setText("Cash");

        OnlineTransferRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(OnlineTransferRadioBtn);
        OnlineTransferRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        OnlineTransferRadioBtn.setText("Online Transfer");

        BankRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(BankRadioBtn);
        BankRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        BankRadioBtn.setText("Bank Deposit");

        ChequeRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(ChequeRadioBtn);
        ChequeRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        ChequeRadioBtn.setText("Cheque");

        VisaRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(VisaRadioBtn);
        VisaRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        VisaRadioBtn.setText("Visa");

        MasterRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(MasterRadioBtn);
        MasterRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        MasterRadioBtn.setText("Master");

        AmexRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(AmexRadioBtn);
        AmexRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        AmexRadioBtn.setText("AMEX");

        CreditRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        ReceptTypeBtnGroup.add(CreditRadioBtn);
        CreditRadioBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        CreditRadioBtn.setText("Credit");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        NoteLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        NoteLbl.setText("Note");

        jScrollPane1.setViewportView(ReceptNote);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoiceNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GrandTotalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CashRadioBtn)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(OnlineTransferRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(BankRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChequeRadioBtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VisaRadioBtn))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasterRadioBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmexRadioBtn))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreditRadioBtn))
                        .addGap(22, 22, 22))
                    .addComponent(jScrollPane1)
                    .addComponent(NoteLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GenarateReceptBtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvoiceNumberLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrandTotalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CashRadioBtn)
                    .addComponent(ChequeRadioBtn)
                    .addComponent(VisaRadioBtn)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BankRadioBtn)
                        .addComponent(MasterRadioBtn)
                        .addComponent(AmexRadioBtn)
                        .addComponent(OnlineTransferRadioBtn))
                    .addComponent(CreditRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenarateReceptBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenarateReceptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenarateReceptBtnMouseClicked

        CashRadioBtn.setActionCommand("Cash");
        OnlineTransferRadioBtn.setActionCommand("Online Transfer");
        BankRadioBtn.setActionCommand("Bank Deposit");
        ChequeRadioBtn.setActionCommand("Cheque");
        VisaRadioBtn.setActionCommand("Visa");
        MasterRadioBtn.setActionCommand("Master");
        AmexRadioBtn.setActionCommand("Amex");
        CreditRadioBtn.setActionCommand("Credit");

        String ReceptType = ReceptTypeBtnGroup.getSelection().getActionCommand();

        String UserId = String.valueOf(cache.LogUserId);

        try {
            JSONObject jo = ServerController.getJsonObject(WebServiceController.SAVE_INVOICE_DETAILS, ServerController.sendSaveInvoiceParams(invoiceId,UserId,ReceptType));
            if (jo != null) {

                if (jo.getBoolean("result")) {

                    //JSONArray array = jo.getJSONArray("msg");
                    //JOptionPane.showMessageDialog(this, "Invoice save successfully.");
                    //Home.showPanel(clientList1);
                    new InvoiceViewDialog(null, pressed, invoiceId).setVisible(true);
                    this.dispose();

                    if(Invoice.invoiceView != null){
                        Invoice.invoiceView.dispose();
                    }

                } else {
                    System.out.println("error");
                    JOptionPane.showMessageDialog(this, "Error saving invoice.");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_GenarateReceptBtnMouseClicked

    private void GenarateReceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenarateReceptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenarateReceptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRecept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRecept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRecept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRecept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateRecept dialog = new CreateRecept(new javax.swing.JFrame(), true, 0, 0.0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AmexRadioBtn;
    private javax.swing.JRadioButton BankRadioBtn;
    private javax.swing.JRadioButton CashRadioBtn;
    private javax.swing.JRadioButton ChequeRadioBtn;
    private javax.swing.JRadioButton CreditRadioBtn;
    private javax.swing.JButton GenarateReceptBtn;
    private javax.swing.JLabel GrandTotalLbl;
    private javax.swing.JLabel InvoiceNumberLbl;
    private javax.swing.JRadioButton MasterRadioBtn;
    private javax.swing.JLabel NoteLbl;
    private javax.swing.JRadioButton OnlineTransferRadioBtn;
    private javax.swing.JEditorPane ReceptNote;
    private javax.swing.ButtonGroup ReceptTypeBtnGroup;
    private javax.swing.JRadioButton VisaRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
