package smartretailer;

import Dialog.cache;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class Home extends javax.swing.JFrame {

	public static JPanel clientsNavView;
	public static JPanel stockNavView;
	public static JPanel invoiceNavView;
	public static JPanel SupplierNavView;
	public static JPanel salesReportNavView;
	private static javax.swing.JPanel PageChangePanel;
	private javax.swing.JLabel UserNameLabel;
	private Pages.ClientsNav clientsNav1;
	private Pages.Dashboard dashboard1;
	private Pages.InvoicesNav invoicesNav1;
	private Pages.SalesReportNav salesReportNav1;
	private Pages.StockNav stockNav2;
	private Pages.SupplierNav supplierNav1;

	public static Home home;

	public Home() {
		initComponents();

		home = this;
		setTitle("Smart Retailer | AMAZOFT");

		clientsNavView = clientsNav1;
		stockNavView = stockNav2;
		invoiceNavView = invoicesNav1;
		SupplierNavView = supplierNav1;
		salesReportNavView = salesReportNav1;
//		projectsNavView = projectsNav1;

		UserNameLabel.setText(cache.LogUserName);
		this.setExtendedState(Invoice.MAXIMIZED_BOTH);
	}


	public static void showPanel(JPanel panel) {

		PageChangePanel.removeAll();
		PageChangePanel.add(panel);
		panel.setVisible(true);
		PageChangePanel.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		JPanel jPanel1 = new JPanel();
		JPanel navigationPanel = new JPanel();
		JLabel jLabel1 = new JLabel();
		JButton dashboardBtn = new JButton();
		UserNameLabel = new javax.swing.JLabel();
		JButton invoicesBtn = new JButton();
		JPanel headerPanel = new JPanel();
		JButton logOutBtn = new JButton();
		JLabel headerLabel = new JLabel();
		PageChangePanel = new javax.swing.JPanel();
		dashboard1 = new Pages.Dashboard();
		stockNav2 = new Pages.StockNav();
		invoicesNav1 = new Pages.InvoicesNav();
		clientsNav1 = new Pages.ClientsNav();
		supplierNav1 = new Pages.SupplierNav();
		salesReportNav1 = new Pages.SalesReportNav();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(1024, 768));
		setPreferredSize(new java.awt.Dimension(1366, 768));

		jPanel1.setBackground(new java.awt.Color(241, 193, 193));

		navigationPanel.setBackground(new java.awt.Color(255, 255, 255, 255));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Images/rr.png")))); // NOI18N

		dashboardBtn.setFont(new java.awt.Font("Helvetica Neue", Font.PLAIN, 18)); // NOI18N
		dashboardBtn.setText("Dashboard");
		dashboardBtn.addActionListener(_ -> DashboardBtnActionPerformed());

		UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		UserNameLabel.setText("Admin");

		invoicesBtn.setFont(new java.awt.Font("Helvetica Neue", Font.PLAIN, 18)); // NOI18N
		invoicesBtn.setText("Invoices");
		invoicesBtn.addActionListener(_ -> InvoicesBtnActionPerformed());


		javax.swing.GroupLayout NavigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
		navigationPanel.setLayout(NavigationPanelLayout);
		NavigationPanelLayout.setHorizontalGroup(
			NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(NavigationPanelLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(dashboardBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(invoicesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
					.addContainerGap())
		);
		NavigationPanelLayout.setVerticalGroup(
			NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(NavigationPanelLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(invoicesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		headerPanel.setBackground(new java.awt.Color(255, 255, 255));

		logOutBtn.setBackground(new java.awt.Color(0, 0, 0));
		logOutBtn.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Images/logout.png")))); // NOI18N
		logOutBtn.addActionListener(this::LogOutBtnActionPerformed);

		headerLabel.setFont(new java.awt.Font("Helvetica Neue", Font.PLAIN, 36)); // NOI18N
		headerLabel.setText("Dashboard");

		javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(headerPanel);
		headerPanel.setLayout(HeaderPanelLayout);
		HeaderPanelLayout.setHorizontalGroup(
			HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(invoicesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		HeaderPanelLayout.setVerticalGroup(
			HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(HeaderPanelLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(invoicesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
					.addContainerGap())
		);


		PageChangePanel.setLayout(new java.awt.CardLayout());
		PageChangePanel.add(dashboard1, "card2");
		PageChangePanel.add(invoicesNav1, "card5");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(PageChangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(PageChangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 2269, Short.MAX_VALUE))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		pack();
		setLocationRelativeTo(null);
	}

	private void DashboardBtnActionPerformed() {
		showPanel(dashboard1);
	}

	private void InvoicesBtnActionPerformed() {
		showPanel(invoicesNav1);
	}

	private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {
		new Login().setVisible(true);
		this.dispose();
	}

	public static void main(String[] args) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
				 UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
	}
}
