/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pages;

import Dialog.cache;
import smartretailer.Home;
import smartretailer.Invoice;
import controllers.ServerController;
import controllers.WebServiceController;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Oshan
 */
public class InvoicesNav extends javax.swing.JPanel {

    /**
     * Creates new form InvoicesNav
     */
    private Thread InvoiceCheckThread;
    private static int InvoiceOngoingCount;
    private static int InvoiceID;

    public InvoicesNav() {
        initComponents();
        invoice_nav_view.setVisible(true);

    }

    public static void showPanel(JPanel panel){

        InvoicePageChangeArea.removeAll();
        InvoicePageChangeArea.add(panel);
        panel.setVisible(true);
        InvoicePageChangeArea.repaint();

    }

    public void loadInvoiceData(){
        CheckInvoiceData();
    }

    private void CheckInvoiceData(){
        InvoiceCheckThread = new Thread(new Runnable() {
        @Override
        public void run() {

            String UserId = String.valueOf(cache.LogUserId);

            try {
                 JSONObject jo = ServerController.getJsonObject(WebServiceController.CHECK_INVOICE_STAT, ServerController.getInvoiceCheckParams(UserId));
            if(jo != null){

                if(jo.getBoolean("result")){


                    JSONArray array = jo.getJSONArray("data");

                    for(int i = 0; i<array.length() ;i++){

                            JSONObject pd = array.getJSONObject(i);

                            int InvoiceOngoingCount = pd.getInt("InvoiceOngoingCount");
                            int InvoiceID = pd.getInt("InvoiceID");

                            InvoicesNav.InvoiceOngoingCount=InvoiceOngoingCount;
                            InvoicesNav.InvoiceID=InvoiceID;

                    }

                        if(InvoiceOngoingCount == 0){
                            invoiceTypeCreate1.loadData();
                            Home.showPanel(invoiceTypeCreate1);
                        }else{
                            int invoiceId = InvoiceID;
                            Invoice inv = new Invoice(invoiceId);
                            inv.setVisible(true);
                        }






                }else{
                    System.out.println("error");
                }

            }

            } catch (Exception e) {
                e.printStackTrace();
            }


        }

        });


        InvoiceCheckThread.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoicePageChangeArea = new javax.swing.JPanel();
        invoice_nav_view = new javax.swing.JPanel();
        CreateInvoiceBtn = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        InvoiceHistoryBtn = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        invoiceTypeCreate1 = new Pages.InvoiceTypeCreate();
        invoiceHistory1 = new Pages.InvoiceHistory();

        setPreferredSize(new java.awt.Dimension(1162, 810));

        InvoicePageChangeArea.setLayout(new java.awt.CardLayout());

        invoice_nav_view.setBackground(new java.awt.Color(255, 255, 255));

        CreateInvoiceBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateInvoiceBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        CreateInvoiceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateInvoiceBtnMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Create Invoice");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create_invoice.png"))); // NOI18N

        javax.swing.GroupLayout CreateInvoiceBtnLayout = new javax.swing.GroupLayout(CreateInvoiceBtn);
        CreateInvoiceBtn.setLayout(CreateInvoiceBtnLayout);
        CreateInvoiceBtnLayout.setHorizontalGroup(
            CreateInvoiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addGroup(CreateInvoiceBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CreateInvoiceBtnLayout.setVerticalGroup(
            CreateInvoiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInvoiceBtnLayout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        invoice_nav_view.add(CreateInvoiceBtn);

        InvoiceHistoryBtn.setBackground(new java.awt.Color(255, 255, 255));
        InvoiceHistoryBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        InvoiceHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InvoiceHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceHistoryBtnMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Invoice History");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice_history.png"))); // NOI18N

        javax.swing.GroupLayout InvoiceHistoryBtnLayout = new javax.swing.GroupLayout(InvoiceHistoryBtn);
        InvoiceHistoryBtn.setLayout(InvoiceHistoryBtnLayout);
        InvoiceHistoryBtnLayout.setHorizontalGroup(
            InvoiceHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InvoiceHistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        InvoiceHistoryBtnLayout.setVerticalGroup(
            InvoiceHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceHistoryBtnLayout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        invoice_nav_view.add(InvoiceHistoryBtn);

        InvoicePageChangeArea.add(invoice_nav_view, "card2");
        InvoicePageChangeArea.add(invoiceTypeCreate1, "card3");
        InvoicePageChangeArea.add(invoiceHistory1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoicePageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoicePageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InvoiceHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceHistoryBtnMouseClicked
        invoiceHistory1.loadData();
        Home.showPanel(invoiceHistory1);
    }//GEN-LAST:event_InvoiceHistoryBtnMouseClicked

    private void CreateInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateInvoiceBtnMouseClicked

        loadInvoiceData();

    }//GEN-LAST:event_CreateInvoiceBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateInvoiceBtn;
    private javax.swing.JPanel InvoiceHistoryBtn;
    public static javax.swing.JPanel InvoicePageChangeArea;
    private Pages.InvoiceHistory invoiceHistory1;
    private Pages.InvoiceTypeCreate invoiceTypeCreate1;
    private javax.swing.JPanel invoice_nav_view;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    // End of variables declaration//GEN-END:variables
}
