/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pages;

import Dialog.cache;
import smartretailer.Home;
import smartretailer.Login;
import controllers.ServerController;
import controllers.WebServiceController;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Oshan
 */
public class SettingsPage extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPage
     */
    private final DefaultTableModel dtm;
    private Thread alluserThread;
    private Thread ShopDetailsThread;
    private Thread VatDetailsThread;

    public SettingsPage() {
        initComponents();

        UpdateNameArea.setVisible(false);
        UpdateContactNumberArea.setVisible(false);
        UpdatePasswordArea.setVisible(false);

        CancelNameUpdateBtn.setVisible(false);
        CancelContactNumberUpdateBtn.setVisible(false);
        CancelPasswordUpdateBtn.setVisible(false);

        String UserId = String.valueOf(cache.LogUserId);
        String UserName = String.valueOf(cache.LogUserName);
        String UserEmail = String.valueOf(cache.LogUserEmail);
        String UserContactNumber = String.valueOf(cache.LogUserTel);
        String UserLevel = String.valueOf(cache.LogUserLevel);

        UserNameLbl.setText(UserName);
        NewNameField.setText(UserName);

        ContactNumberLbl.setText(UserContactNumber);
        NewContactNumberField.setText(UserContactNumber);
        ///
        UserEmailLbl.setText(UserEmail);

        dtm = (DefaultTableModel) UserTbl.getModel();


        //User Role Check and view
        if("1".equals(UserLevel)){
            //View Users
            AllUsersLoadArea.setVisible(true);
            PermisionCheckingAllUserArea.setVisible(false);
            //Reg Users
            UserRegisterArea.setVisible(true);
            PermisionCheckingRegisterUserArea.setVisible(false);
            //Shop Details Users
            ShopDetailsUpdateArea.setVisible(true);
            PermisionCheckingShopDetailsArea.setVisible(false);
            //Invoice Details Users
            InvoiceDetailsUpdateArea.setVisible(true);
            PermisionCheckingInvoiceDetailsArea.setVisible(false);
        }else{
            //View Users
            AllUsersLoadArea.setVisible(false);
            PermisionCheckingAllUserArea.setVisible(true);
            //Reg Users
            UserRegisterArea.setVisible(false);
            PermisionCheckingRegisterUserArea.setVisible(true);
            //Shop Details Users
            ShopDetailsUpdateArea.setVisible(false);
            PermisionCheckingShopDetailsArea.setVisible(true);
            //Invoice Details Users
            InvoiceDetailsUpdateArea.setVisible(false);
            PermisionCheckingInvoiceDetailsArea.setVisible(true);
        }


    }

    public void loadData(){
       LoadAllUsersData();
       LoadShopData();
       LoadVatData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AccountDetailsArea = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserNameLbl = new javax.swing.JLabel();
        EditUserNameBtn = new javax.swing.JButton();
        UpdateNameArea = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NewNameField = new javax.swing.JTextField();
        SaveNameBtn = new javax.swing.JButton();
        CancelNameUpdateBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UserEmailLbl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ContactNumberLbl = new javax.swing.JLabel();
        EditContactNumberBtn = new javax.swing.JButton();
        UpdateContactNumberArea = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NewContactNumberField = new javax.swing.JTextField();
        SaveContactNumberBtn = new javax.swing.JButton();
        CancelContactNumberUpdateBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        UserNameLbl2 = new javax.swing.JLabel();
        EditPasswordBtn = new javax.swing.JButton();
        UpdatePasswordArea = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SavePasswordBtn = new javax.swing.JButton();
        PasswordChangeField = new javax.swing.JPasswordField();
        CancelPasswordUpdateBtn = new javax.swing.JButton();
        CreateUsersArea = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        UserRegisterArea = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        FirstNameLbl = new javax.swing.JLabel();
        VNewUserNameField = new javax.swing.JTextField();
        LastNameLbl = new javax.swing.JLabel();
        VNewEmailField = new javax.swing.JTextField();
        FirstNameLbl1 = new javax.swing.JLabel();
        VContactNumberField = new javax.swing.JTextField();
        LastNameLbl1 = new javax.swing.JLabel();
        FirstNameLbl2 = new javax.swing.JLabel();
        VPasswordField = new javax.swing.JPasswordField();
        CreateAccountBtn = new javax.swing.JButton();
        ClearAccountBtn = new javax.swing.JButton();
        VUserRoleField = new javax.swing.JComboBox<>();
        PermisionCheckingRegisterUserArea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AllUsersArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        AllUsersLoadArea = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UserTbl = new javax.swing.JTable();
        PermisionCheckingAllUserArea = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ShopDetailsArea = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        ShopDetailsUpdateArea = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        FirstNameLbl3 = new javax.swing.JLabel();
        ShopNameField = new javax.swing.JTextField();
        LastNameLbl2 = new javax.swing.JLabel();
        ShopEmailField = new javax.swing.JTextField();
        FirstNameLbl4 = new javax.swing.JLabel();
        ShopContactNumberField = new javax.swing.JTextField();
        LastNameLbl3 = new javax.swing.JLabel();
        FirstNameLbl5 = new javax.swing.JLabel();
        UpdateShopDetails = new javax.swing.JButton();
        ClearShopDetails = new javax.swing.JButton();
        ShopAddressField = new javax.swing.JTextField();
        ShopRodatNameField = new javax.swing.JTextField();
        ShopCityField = new javax.swing.JTextField();
        LastNameLbl4 = new javax.swing.JLabel();
        ShopCountryField = new javax.swing.JTextField();
        FirstNameLbl6 = new javax.swing.JLabel();
        PermisionCheckingShopDetailsArea = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        InvoiceDetailsArea = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        InvoiceDetailsUpdateArea = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        FirstNameLbl7 = new javax.swing.JLabel();
        InvoiceVatField = new javax.swing.JTextField();
        UpdateVATDetailsBtn = new javax.swing.JButton();
        PermisionCheckingInvoiceDetailsArea = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1162, 810));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Settings");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setText("Name");

        UserNameLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        UserNameLbl.setText("Demo Name");

        EditUserNameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        EditUserNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserNameBtnActionPerformed(evt);
            }
        });

        UpdateNameArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Name");

        NewNameField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        SaveNameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        SaveNameBtn.setText("Save Changes");
        SaveNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateNameAreaLayout = new javax.swing.GroupLayout(UpdateNameArea);
        UpdateNameArea.setLayout(UpdateNameAreaLayout);
        UpdateNameAreaLayout.setHorizontalGroup(
            UpdateNameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateNameAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateNameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateNameAreaLayout.createSequentialGroup()
                        .addComponent(SaveNameBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(NewNameField))
                .addContainerGap())
        );
        UpdateNameAreaLayout.setVerticalGroup(
            UpdateNameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateNameAreaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(UpdateNameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveNameBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CancelNameUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        CancelNameUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelNameUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateNameArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelNameUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditUserNameBtn)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(UserNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CancelNameUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditUserNameBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("Email Address");

        UserEmailLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        UserEmailLbl.setText("johndoe@mail.com");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(UserEmailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setText("Contact Number");

        ContactNumberLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ContactNumberLbl.setText("0771188218");

        EditContactNumberBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        EditContactNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditContactNumberBtnActionPerformed(evt);
            }
        });

        UpdateContactNumberArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Contact Number");

        NewContactNumberField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        SaveContactNumberBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        SaveContactNumberBtn.setText("Save Changes");
        SaveContactNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveContactNumberBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateContactNumberAreaLayout = new javax.swing.GroupLayout(UpdateContactNumberArea);
        UpdateContactNumberArea.setLayout(UpdateContactNumberAreaLayout);
        UpdateContactNumberAreaLayout.setHorizontalGroup(
            UpdateContactNumberAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateContactNumberAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateContactNumberAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateContactNumberAreaLayout.createSequentialGroup()
                        .addComponent(SaveContactNumberBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(NewContactNumberField))
                .addContainerGap())
        );
        UpdateContactNumberAreaLayout.setVerticalGroup(
            UpdateContactNumberAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateContactNumberAreaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(UpdateContactNumberAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewContactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveContactNumberBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CancelContactNumberUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        CancelContactNumberUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelContactNumberUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateContactNumberArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(CancelContactNumberUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditContactNumberBtn)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(ContactNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditContactNumberBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelContactNumberUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateContactNumberArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setText("Change Password");

        UserNameLbl2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        UserNameLbl2.setText("It's a good idea to use a strong password that you don't use elsewhere ");

        EditPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        EditPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPasswordBtnActionPerformed(evt);
            }
        });

        UpdatePasswordArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("New Password");

        SavePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        SavePasswordBtn.setText("Save Changes");
        SavePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePasswordBtnActionPerformed(evt);
            }
        });

        PasswordChangeField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        javax.swing.GroupLayout UpdatePasswordAreaLayout = new javax.swing.GroupLayout(UpdatePasswordArea);
        UpdatePasswordArea.setLayout(UpdatePasswordAreaLayout);
        UpdatePasswordAreaLayout.setHorizontalGroup(
            UpdatePasswordAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePasswordAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePasswordAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePasswordAreaLayout.createSequentialGroup()
                        .addComponent(SavePasswordBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PasswordChangeField))
                .addContainerGap())
        );
        UpdatePasswordAreaLayout.setVerticalGroup(
            UpdatePasswordAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePasswordAreaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(UpdatePasswordAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordChangeField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SavePasswordBtn)
                .addGap(11, 11, 11))
        );

        CancelPasswordUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        CancelPasswordUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelPasswordUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdatePasswordArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(CancelPasswordUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditPasswordBtn)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(UserNameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelPasswordUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditPasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdatePasswordArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout AccountDetailsAreaLayout = new javax.swing.GroupLayout(AccountDetailsArea);
        AccountDetailsArea.setLayout(AccountDetailsAreaLayout);
        AccountDetailsAreaLayout.setHorizontalGroup(
            AccountDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        AccountDetailsAreaLayout.setVerticalGroup(
            AccountDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Account Details", AccountDetailsArea);

        CreateUsersArea.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        UserRegisterArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel12.setText("Create Users");

        FirstNameLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl.setText("Type Name *");

        VNewUserNameField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        LastNameLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        LastNameLbl.setText("Email *");

        VNewEmailField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        FirstNameLbl1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl1.setText("Contact Number *");

        VContactNumberField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        LastNameLbl1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        LastNameLbl1.setText("User Role *");

        FirstNameLbl2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl2.setText("Password *");

        CreateAccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        CreateAccountBtn.setText("Create Account");
        CreateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountBtnActionPerformed(evt);
            }
        });

        ClearAccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        ClearAccountBtn.setText("Clear");
        ClearAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAccountBtnActionPerformed(evt);
            }
        });

        VUserRoleField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Account", "Admin Account" }));

        javax.swing.GroupLayout UserRegisterAreaLayout = new javax.swing.GroupLayout(UserRegisterArea);
        UserRegisterArea.setLayout(UserRegisterAreaLayout);
        UserRegisterAreaLayout.setHorizontalGroup(
            UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                    .addGroup(UserRegisterAreaLayout.createSequentialGroup()
                        .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VNewUserNameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VNewEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegisterAreaLayout.createSequentialGroup()
                        .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VContactNumberField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(VUserRoleField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(FirstNameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VPasswordField)
                    .addGroup(UserRegisterAreaLayout.createSequentialGroup()
                        .addComponent(CreateAccountBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearAccountBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UserRegisterAreaLayout.setVerticalGroup(
            UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLbl)
                    .addComponent(LastNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VNewUserNameField)
                    .addComponent(VNewEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLbl1)
                    .addComponent(LastNameLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VContactNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(VUserRoleField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAccountBtn)
                    .addComponent(ClearAccountBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PermisionCheckingRegisterUserArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("You don't have Permission to create user accounts");

        javax.swing.GroupLayout PermisionCheckingRegisterUserAreaLayout = new javax.swing.GroupLayout(PermisionCheckingRegisterUserArea);
        PermisionCheckingRegisterUserArea.setLayout(PermisionCheckingRegisterUserAreaLayout);
        PermisionCheckingRegisterUserAreaLayout.setHorizontalGroup(
            PermisionCheckingRegisterUserAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PermisionCheckingRegisterUserAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                .addContainerGap())
        );
        PermisionCheckingRegisterUserAreaLayout.setVerticalGroup(
            PermisionCheckingRegisterUserAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermisionCheckingRegisterUserAreaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserRegisterArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PermisionCheckingRegisterUserArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(UserRegisterArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermisionCheckingRegisterUserArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel13);

        javax.swing.GroupLayout CreateUsersAreaLayout = new javax.swing.GroupLayout(CreateUsersArea);
        CreateUsersArea.setLayout(CreateUsersAreaLayout);
        CreateUsersAreaLayout.setHorizontalGroup(
            CreateUsersAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        CreateUsersAreaLayout.setVerticalGroup(
            CreateUsersAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jTabbedPane1.addTab("Create Users", CreateUsersArea);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        AllUsersLoadArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel10.setText("Users List");

        UserTbl.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        UserTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "Email", "Role", "Contact Number", "Register Date", "UserId"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(UserTbl);
        if (UserTbl.getColumnModel().getColumnCount() > 0) {
            UserTbl.getColumnModel().getColumn(0).setMinWidth(50);
            UserTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
            UserTbl.getColumnModel().getColumn(0).setMaxWidth(50);
            UserTbl.getColumnModel().getColumn(6).setMinWidth(0);
            UserTbl.getColumnModel().getColumn(6).setPreferredWidth(0);
            UserTbl.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        javax.swing.GroupLayout AllUsersLoadAreaLayout = new javax.swing.GroupLayout(AllUsersLoadArea);
        AllUsersLoadArea.setLayout(AllUsersLoadAreaLayout);
        AllUsersLoadAreaLayout.setHorizontalGroup(
            AllUsersLoadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllUsersLoadAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AllUsersLoadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        AllUsersLoadAreaLayout.setVerticalGroup(
            AllUsersLoadAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllUsersLoadAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PermisionCheckingAllUserArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("You don't have Permission to view user accounts");

        javax.swing.GroupLayout PermisionCheckingAllUserAreaLayout = new javax.swing.GroupLayout(PermisionCheckingAllUserArea);
        PermisionCheckingAllUserArea.setLayout(PermisionCheckingAllUserAreaLayout);
        PermisionCheckingAllUserAreaLayout.setHorizontalGroup(
            PermisionCheckingAllUserAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PermisionCheckingAllUserAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                .addContainerGap())
        );
        PermisionCheckingAllUserAreaLayout.setVerticalGroup(
            PermisionCheckingAllUserAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermisionCheckingAllUserAreaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllUsersLoadArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PermisionCheckingAllUserArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(AllUsersLoadArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermisionCheckingAllUserArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel12);

        javax.swing.GroupLayout AllUsersAreaLayout = new javax.swing.GroupLayout(AllUsersArea);
        AllUsersArea.setLayout(AllUsersAreaLayout);
        AllUsersAreaLayout.setHorizontalGroup(
            AllUsersAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        AllUsersAreaLayout.setVerticalGroup(
            AllUsersAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jTabbedPane1.addTab("All Users", AllUsersArea);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        ShopDetailsUpdateArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel14.setText("Shop Details");

        FirstNameLbl3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl3.setText("Shop Name *");

        ShopNameField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        LastNameLbl2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        LastNameLbl2.setText("Shop Email *");

        ShopEmailField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        FirstNameLbl4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl4.setText("Shop Contact Number *");

        ShopContactNumberField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        LastNameLbl3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        LastNameLbl3.setText("Shop Address *");

        FirstNameLbl5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl5.setText("Shop Road Name *");

        UpdateShopDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        UpdateShopDetails.setText("Update Details");
        UpdateShopDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateShopDetailsActionPerformed(evt);
            }
        });

        ClearShopDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        ClearShopDetails.setText("Clear");
        ClearShopDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearShopDetailsActionPerformed(evt);
            }
        });

        ShopAddressField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        ShopRodatNameField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        ShopCityField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        LastNameLbl4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        LastNameLbl4.setText("Shop City *");

        ShopCountryField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        FirstNameLbl6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl6.setText("Shop Country *");

        javax.swing.GroupLayout ShopDetailsUpdateAreaLayout = new javax.swing.GroupLayout(ShopDetailsUpdateArea);
        ShopDetailsUpdateArea.setLayout(ShopDetailsUpdateAreaLayout);
        ShopDetailsUpdateAreaLayout.setHorizontalGroup(
            ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                    .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                        .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShopNameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShopEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)))
                    .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                        .addComponent(UpdateShopDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearShopDetails)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShopDetailsUpdateAreaLayout.createSequentialGroup()
                        .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ShopCountryField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLbl6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameLbl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameLbl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShopContactNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShopRodatNameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShopAddressField)
                            .addComponent(LastNameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShopCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        ShopDetailsUpdateAreaLayout.setVerticalGroup(
            ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLbl3)
                    .addComponent(LastNameLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShopNameField)
                    .addComponent(ShopEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLbl4)
                    .addComponent(LastNameLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShopContactNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ShopAddressField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                        .addComponent(FirstNameLbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShopRodatNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShopDetailsUpdateAreaLayout.createSequentialGroup()
                        .addComponent(LastNameLbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShopCityField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameLbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShopCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ShopDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateShopDetails)
                    .addComponent(ClearShopDetails))
                .addContainerGap())
        );

        PermisionCheckingShopDetailsArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("You don't have Permission to update shop details");

        javax.swing.GroupLayout PermisionCheckingShopDetailsAreaLayout = new javax.swing.GroupLayout(PermisionCheckingShopDetailsArea);
        PermisionCheckingShopDetailsArea.setLayout(PermisionCheckingShopDetailsAreaLayout);
        PermisionCheckingShopDetailsAreaLayout.setHorizontalGroup(
            PermisionCheckingShopDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PermisionCheckingShopDetailsAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                .addContainerGap())
        );
        PermisionCheckingShopDetailsAreaLayout.setVerticalGroup(
            PermisionCheckingShopDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermisionCheckingShopDetailsAreaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShopDetailsUpdateArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PermisionCheckingShopDetailsArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(ShopDetailsUpdateArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermisionCheckingShopDetailsArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel14);

        javax.swing.GroupLayout ShopDetailsAreaLayout = new javax.swing.GroupLayout(ShopDetailsArea);
        ShopDetailsArea.setLayout(ShopDetailsAreaLayout);
        ShopDetailsAreaLayout.setHorizontalGroup(
            ShopDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        ShopDetailsAreaLayout.setVerticalGroup(
            ShopDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Shop Details", ShopDetailsArea);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        InvoiceDetailsUpdateArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel16.setText("Invoice Details");

        FirstNameLbl7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        FirstNameLbl7.setText("VAT (%) *");

        InvoiceVatField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        UpdateVATDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        UpdateVATDetailsBtn.setText("Update VAT");
        UpdateVATDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVATDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoiceDetailsUpdateAreaLayout = new javax.swing.GroupLayout(InvoiceDetailsUpdateArea);
        InvoiceDetailsUpdateArea.setLayout(InvoiceDetailsUpdateAreaLayout);
        InvoiceDetailsUpdateAreaLayout.setHorizontalGroup(
            InvoiceDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceDetailsUpdateAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoiceDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                    .addGroup(InvoiceDetailsUpdateAreaLayout.createSequentialGroup()
                        .addGroup(InvoiceDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvoiceVatField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateVATDetailsBtn)
                        .addGap(457, 457, 457)))
                .addContainerGap())
        );
        InvoiceDetailsUpdateAreaLayout.setVerticalGroup(
            InvoiceDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceDetailsUpdateAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameLbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InvoiceDetailsUpdateAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvoiceVatField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateVATDetailsBtn))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        PermisionCheckingInvoiceDetailsArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("You don't have Permission to update invoice details");

        javax.swing.GroupLayout PermisionCheckingInvoiceDetailsAreaLayout = new javax.swing.GroupLayout(PermisionCheckingInvoiceDetailsArea);
        PermisionCheckingInvoiceDetailsArea.setLayout(PermisionCheckingInvoiceDetailsAreaLayout);
        PermisionCheckingInvoiceDetailsAreaLayout.setHorizontalGroup(
            PermisionCheckingInvoiceDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PermisionCheckingInvoiceDetailsAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                .addContainerGap())
        );
        PermisionCheckingInvoiceDetailsAreaLayout.setVerticalGroup(
            PermisionCheckingInvoiceDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermisionCheckingInvoiceDetailsAreaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoiceDetailsUpdateArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PermisionCheckingInvoiceDetailsArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(InvoiceDetailsUpdateArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermisionCheckingInvoiceDetailsArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel15);

        javax.swing.GroupLayout InvoiceDetailsAreaLayout = new javax.swing.GroupLayout(InvoiceDetailsArea);
        InvoiceDetailsArea.setLayout(InvoiceDetailsAreaLayout);
        InvoiceDetailsAreaLayout.setHorizontalGroup(
            InvoiceDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        InvoiceDetailsAreaLayout.setVerticalGroup(
            InvoiceDetailsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Invoice Details", InvoiceDetailsArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateVATDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVATDetailsBtnActionPerformed

        if(InvoiceVatField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String NewVatRate = InvoiceVatField.getText();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.UPDATE_VAT_DETAILS, ServerController.sendVatDetailsParams(NewVatRate));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "VAT rate updated successfully.");
                        loadData();

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error updating VAT rate, Please try again.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_UpdateVATDetailsBtnActionPerformed

    private void ClearShopDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearShopDetailsActionPerformed
        ShopNameField.setText("");
        ShopEmailField.setText("");
        ShopContactNumberField.setText("");
        ShopAddressField.setText("");
        ShopRodatNameField.setText("");
        ShopCityField.setText("");
        ShopCountryField.setText("");
    }//GEN-LAST:event_ClearShopDetailsActionPerformed

    private void UpdateShopDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateShopDetailsActionPerformed

        if(ShopNameField.getText().isEmpty() || ShopEmailField.getText().isEmpty() || ShopContactNumberField.getText().isEmpty() || ShopAddressField.getText().isEmpty() || ShopRodatNameField.getText().isEmpty() || ShopCityField.getText().isEmpty() || ShopCountryField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String ShopName = ShopNameField.getText();
            String ShopEmail = ShopEmailField.getText();
            String ShopTel = ShopContactNumberField.getText();
            String ShopAddress = ShopAddressField.getText();
            String ShopRoadName = ShopRodatNameField.getText();
            String ShopCityName = ShopCityField.getText();
            String ShopCountryName = ShopCountryField.getText();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.UPDATE_SHOP_DETAILS, ServerController.sendShopDetailsParams(ShopName,ShopEmail,ShopTel,ShopAddress,ShopRoadName,ShopCityName,ShopCountryName));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "Shop details updated successfully.");
                        loadData();

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error updating shop details, Please try again.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_UpdateShopDetailsActionPerformed

    private void ClearAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAccountBtnActionPerformed
        VNewUserNameField.setText("");
        VNewEmailField.setText("");
        VContactNumberField.setText("");
        VPasswordField.setText("");
    }//GEN-LAST:event_ClearAccountBtnActionPerformed

    private void CreateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountBtnActionPerformed

        if(VNewUserNameField.getText().isEmpty() || VNewEmailField.getText().isEmpty() || VContactNumberField.getText().isEmpty() || VPasswordField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String UserName = VNewUserNameField.getText();
            String UserEmail = VNewEmailField.getText();
            String UserTel = VContactNumberField.getText();
            String UserPassword = VPasswordField.getText();
            String UserRole = VUserRoleField.getSelectedItem().toString();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.CREATE_USER_ACCOUNT, ServerController.createUserAccountParams(UserName,UserEmail,UserTel,UserPassword,UserRole));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "New account create successfully.");

                        VNewUserNameField.setText("");
                        VNewEmailField.setText("");
                        VContactNumberField.setText("");
                        VPasswordField.setText("");

                        loadData();

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error creating account, Please try again.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_CreateAccountBtnActionPerformed

    private void CancelPasswordUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelPasswordUpdateBtnActionPerformed
        UpdatePasswordArea.setVisible(false);
        EditPasswordBtn.setVisible(true);
        CancelPasswordUpdateBtn.setVisible(false);
    }//GEN-LAST:event_CancelPasswordUpdateBtnActionPerformed

    private void SavePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePasswordBtnActionPerformed

        if(PasswordChangeField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String UserId = String.valueOf(cache.LogUserId);
            String NewPassword = PasswordChangeField.getText();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.UPDATE_USER_PASSWORD, ServerController.updateUserPasswordParams(UserId,NewPassword));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "New password update successfully. Please login again.");

                        new Login().setVisible(true);
                        if(Home.home != null){
                            Home.home.dispose();
                        }

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error updating password.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_SavePasswordBtnActionPerformed

    private void EditPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPasswordBtnActionPerformed
        UpdatePasswordArea.setVisible(true);
        EditPasswordBtn.setVisible(false);
        CancelPasswordUpdateBtn.setVisible(true);
    }//GEN-LAST:event_EditPasswordBtnActionPerformed

    private void CancelContactNumberUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelContactNumberUpdateBtnActionPerformed
        UpdateContactNumberArea.setVisible(false);
        EditContactNumberBtn.setVisible(true);
        CancelContactNumberUpdateBtn.setVisible(false);
    }//GEN-LAST:event_CancelContactNumberUpdateBtnActionPerformed

    private void SaveContactNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveContactNumberBtnActionPerformed

        if(NewContactNumberField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String UserId = String.valueOf(cache.LogUserId);
            String UserContactNumber = NewContactNumberField.getText();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.UPDATE_USER_CONTACT_NUMBER, ServerController.updateUserContactNumberParams(UserId,UserContactNumber));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "User contact number update successfully.");
                        String NewUserContactNumber = jo.getString("NewUserContactNumber");

                        ContactNumberLbl.setText(NewUserContactNumber);
                        NewContactNumberField.setText(NewUserContactNumber);

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error updating user contact number.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_SaveContactNumberBtnActionPerformed

    private void EditContactNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditContactNumberBtnActionPerformed
        UpdateContactNumberArea.setVisible(true);
        EditContactNumberBtn.setVisible(false);
        CancelContactNumberUpdateBtn.setVisible(true);
    }//GEN-LAST:event_EditContactNumberBtnActionPerformed

    private void CancelNameUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelNameUpdateBtnActionPerformed
        UpdateNameArea.setVisible(false);
        EditUserNameBtn.setVisible(true);
        CancelNameUpdateBtn.setVisible(false);
    }//GEN-LAST:event_CancelNameUpdateBtnActionPerformed

    private void SaveNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNameBtnActionPerformed

        if(NewNameField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the requered(*)  area.");
        }else{

            String UserId = String.valueOf(cache.LogUserId);
            String UserName = NewNameField.getText();

            try {
                JSONObject jo = ServerController.getJsonObject(WebServiceController.UPDATE_USER_NAME, ServerController.updateUserNameParams(UserId,UserName));
                if(jo != null){

                    if(jo.getBoolean("result")){

                        JOptionPane.showMessageDialog(null, "User name update successfully.");
                        String NUserName = jo.getString("NewUserName");

                        UserNameLbl.setText(NUserName);
                        NewNameField.setText(NUserName);

                    }else{
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Error updating user name.");
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_SaveNameBtnActionPerformed

    private void EditUserNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserNameBtnActionPerformed
        UpdateNameArea.setVisible(true);
        EditUserNameBtn.setVisible(false);
        CancelNameUpdateBtn.setVisible(true);
    }//GEN-LAST:event_EditUserNameBtnActionPerformed

    private void LoadVatData(){

        VatDetailsThread = new Thread(new Runnable() {
        @Override
        public void run() {

            try {
                 JSONObject jo = ServerController.getJsonObject(WebServiceController.DOWNLOAD_VAT_DETAILS, ServerController.getVatDetailsParams("1"));
            if(jo != null){

                if(jo.getBoolean("result")){


                    JSONArray array = jo.getJSONArray("data");

                    for(int i = 0; i<array.length() ;i++){

                            JSONObject pd = array.getJSONObject(i);

                            int VatId = pd.getInt("VatId");
                            String VatPrice = pd.getString("VatPrice");
                            String VatDateTime = pd.getString("VatDateTime");

                            InvoiceVatField.setText(VatPrice);

                    }



                }else{
                    System.out.println("error");
                }

            }

            } catch (Exception e) {
                e.printStackTrace();
            }


        }

        });


        VatDetailsThread.start();

    }

    private void LoadShopData(){

        ShopDetailsThread = new Thread(new Runnable() {
        @Override
        public void run() {

            try {
                 JSONObject jo = ServerController.getJsonObject(WebServiceController.DOWNLOAD_SHOP_DETAILS, ServerController.getShopDetailsParams("1"));
            if(jo != null){

                if(jo.getBoolean("result")){


                    JSONArray array = jo.getJSONArray("data");

                    for(int i = 0; i<array.length() ;i++){

                            JSONObject pd = array.getJSONObject(i);


                            int ShopId = pd.getInt("ShopId");
                            String ShopName = pd.getString("ShopName");
                            String ShopEmail = pd.getString("ShopEmail");
                            String ShopTel = pd.getString("ShopTel");
                            String ShopAddress = pd.getString("ShopAddress");
                            String ShopRoadName = pd.getString("ShopRoadName");
                            String ShopCityName = pd.getString("ShopCityName");
                            String ShopCountryName = pd.getString("ShopCountryName");

                            ShopNameField.setText(ShopName);
                            ShopEmailField.setText(ShopEmail);
                            ShopContactNumberField.setText(ShopTel);
                            ShopAddressField.setText(ShopAddress);
                            ShopRodatNameField.setText(ShopRoadName);
                            ShopCityField.setText(ShopCityName);
                            ShopCountryField.setText(ShopCountryName);

                    }



                }else{
                    System.out.println("error");
                }

            }

            } catch (Exception e) {
                e.printStackTrace();
            }


        }

        });


        ShopDetailsThread.start();

    }

    private void LoadAllUsersData(){
        dtm.setRowCount(0);

        alluserThread = new Thread(new Runnable() {
        @Override
        public void run() {

            String UserId = String.valueOf(cache.LogUserId);

            try {
                 JSONObject jo = ServerController.getJsonObject(WebServiceController.DOWNLOAD_USER_ACCOUNT_LIST, ServerController.getUserAccountListParams(UserId));
            if(jo != null){

                if(jo.getBoolean("result")){


                    JSONArray array = jo.getJSONArray("data");

                    for(int i = 0; i<array.length() ;i++){

                            JSONObject pd = array.getJSONObject(i);

                            int UsersId = pd.getInt("UserId");
                            int UsersAccountCountView = pd.getInt("UserAccountCountView");
                            String UsersName = pd.getString("UserName");
                            String UsersEmail = pd.getString("UserEmail");
                            String UsersRole = pd.getString("UserRole");
                            String UsersTel = pd.getString("UserTel");
                            String UserType = pd.getString("UserType");
                            String UserCreateDate = pd.getString("UserCreateDate");

                            Vector v = new Vector();
                            v.add(UsersAccountCountView+"");
                            v.add(UsersName);
                            v.add(UsersEmail);
                            v.add(UserType);
                            v.add(UsersTel);
                            v.add(UserCreateDate);
                            v.add(UsersId);

                            dtm.addRow(v);

                    }



                }else{
                    System.out.println("error");
                }

            }

            } catch (Exception e) {
                e.printStackTrace();
            }


        }

        });


        alluserThread.start();

    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountDetailsArea;
    private javax.swing.JPanel AllUsersArea;
    private javax.swing.JPanel AllUsersLoadArea;
    private javax.swing.JButton CancelContactNumberUpdateBtn;
    private javax.swing.JButton CancelNameUpdateBtn;
    private javax.swing.JButton CancelPasswordUpdateBtn;
    private javax.swing.JButton ClearAccountBtn;
    private javax.swing.JButton ClearShopDetails;
    private javax.swing.JLabel ContactNumberLbl;
    private javax.swing.JButton CreateAccountBtn;
    private javax.swing.JPanel CreateUsersArea;
    private javax.swing.JButton EditContactNumberBtn;
    private javax.swing.JButton EditPasswordBtn;
    private javax.swing.JButton EditUserNameBtn;
    private javax.swing.JLabel FirstNameLbl;
    private javax.swing.JLabel FirstNameLbl1;
    private javax.swing.JLabel FirstNameLbl2;
    private javax.swing.JLabel FirstNameLbl3;
    private javax.swing.JLabel FirstNameLbl4;
    private javax.swing.JLabel FirstNameLbl5;
    private javax.swing.JLabel FirstNameLbl6;
    private javax.swing.JLabel FirstNameLbl7;
    private javax.swing.JPanel InvoiceDetailsArea;
    private javax.swing.JPanel InvoiceDetailsUpdateArea;
    private javax.swing.JTextField InvoiceVatField;
    private javax.swing.JLabel LastNameLbl;
    private javax.swing.JLabel LastNameLbl1;
    private javax.swing.JLabel LastNameLbl2;
    private javax.swing.JLabel LastNameLbl3;
    private javax.swing.JLabel LastNameLbl4;
    private javax.swing.JTextField NewContactNumberField;
    private javax.swing.JTextField NewNameField;
    private javax.swing.JPasswordField PasswordChangeField;
    private javax.swing.JPanel PermisionCheckingAllUserArea;
    private javax.swing.JPanel PermisionCheckingInvoiceDetailsArea;
    private javax.swing.JPanel PermisionCheckingRegisterUserArea;
    private javax.swing.JPanel PermisionCheckingShopDetailsArea;
    private javax.swing.JButton SaveContactNumberBtn;
    private javax.swing.JButton SaveNameBtn;
    private javax.swing.JButton SavePasswordBtn;
    private javax.swing.JTextField ShopAddressField;
    private javax.swing.JTextField ShopCityField;
    private javax.swing.JTextField ShopContactNumberField;
    private javax.swing.JTextField ShopCountryField;
    private javax.swing.JPanel ShopDetailsArea;
    private javax.swing.JPanel ShopDetailsUpdateArea;
    private javax.swing.JTextField ShopEmailField;
    private javax.swing.JTextField ShopNameField;
    private javax.swing.JTextField ShopRodatNameField;
    private javax.swing.JPanel UpdateContactNumberArea;
    private javax.swing.JPanel UpdateNameArea;
    private javax.swing.JPanel UpdatePasswordArea;
    private javax.swing.JButton UpdateShopDetails;
    private javax.swing.JButton UpdateVATDetailsBtn;
    private javax.swing.JLabel UserEmailLbl;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JLabel UserNameLbl2;
    private javax.swing.JPanel UserRegisterArea;
    private javax.swing.JTable UserTbl;
    private javax.swing.JTextField VContactNumberField;
    private javax.swing.JTextField VNewEmailField;
    private javax.swing.JTextField VNewUserNameField;
    private javax.swing.JPasswordField VPasswordField;
    private javax.swing.JComboBox<String> VUserRoleField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
