/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pages;

import smartretailer.Home;
import controllers.ServerController;
import controllers.WebServiceController;

import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Oshan
 */
public class StockNav extends javax.swing.JPanel {

    /**
     * Creates new form StockNav
     */
    private Thread GrnCheckThread;

    private static int GRNOngoingCount;
    private static int GRNID;

    public StockNav() {
        initComponents();
        stock_nav_view.setVisible(true);

    }

    public static void showPanel(JPanel panel){

        StockPageChangeArea.removeAll();
        StockPageChangeArea.add(panel);
        panel.setVisible(true);
        StockPageChangeArea.repaint();

    }

    public void loadGRNData(){
        CheckGRNData();
    }

    private void CheckGRNData(){
        //dtm.setRowCount(0);


        GrnCheckThread = new Thread(new Runnable() {
        @Override
        public void run() {

            try {
                 JSONObject jo = ServerController.getJsonObject(WebServiceController.CHECK_GRN_STAT, ServerController.getGrnCheckParams("1"));
            if(jo != null){

                if(jo.getBoolean("result")){


                    JSONArray array = jo.getJSONArray("data");

                    for(int i = 0; i<array.length() ;i++){

                            JSONObject pd = array.getJSONObject(i);

                            int GRNOngoingCount = pd.getInt("GRNOngoingCount");
                            int GRNID = pd.getInt("GRNID");

                            StockNav.GRNOngoingCount=GRNOngoingCount;
                            StockNav.GRNID=GRNID;

                    }

                        if(GRNOngoingCount == 0){
                            stockCreateGRN1.loadData();
                            Home.showPanel(stockCreateGRN1);
                        }else{
                            //stockGRNInvoiceCreate1
                            int gid = GRNID;
                            stockGRNInvoiceCreate1.setGrnId(gid);
                            Home.showPanel(stockGRNInvoiceCreate1);
                        }



                }else{
                    System.out.println("error");
                }

            }

            } catch (Exception e) {
                e.printStackTrace();
            }


        }

        });


        GrnCheckThread.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StockPageChangeArea = new javax.swing.JPanel();
        stock_nav_view = new javax.swing.JPanel();
        ViewStockBtn = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        ProductsBtn = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        AddProductsBtn = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        CreateGrnBtn = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ViewGrnBtn = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        SearchProductBtn = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        stockView1 = new Pages.StockView();
        stockGRNList1 = new Pages.StockGRNList();
        stockProducts1 = new Pages.StockProducts();
        stockAddProduct1 = new Pages.StockAddProduct();
        stockSearch1 = new Pages.StockSearch();
        stockCreateGRN1 = new Pages.StockCreateGRN();
        stockGRNInvoiceCreate1 = new Pages.StockGRNInvoiceCreate();

        setPreferredSize(new java.awt.Dimension(1162, 810));

        StockPageChangeArea.setLayout(new java.awt.CardLayout());

        stock_nav_view.setBackground(new java.awt.Color(255, 255, 255));

        ViewStockBtn.setBackground(new java.awt.Color(255, 255, 255));
        ViewStockBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        ViewStockBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        ViewStockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewStockBtnMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("View Stock");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock.png"))); // NOI18N

        javax.swing.GroupLayout ViewStockBtnLayout = new javax.swing.GroupLayout(ViewStockBtn);
        ViewStockBtn.setLayout(ViewStockBtnLayout);
        ViewStockBtnLayout.setHorizontalGroup(
            ViewStockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewStockBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        ViewStockBtnLayout.setVerticalGroup(
            ViewStockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewStockBtnLayout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(ViewStockBtn);

        ProductsBtn.setBackground(new java.awt.Color(255, 255, 255));
        ProductsBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        ProductsBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        ProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsBtnMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Products");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/products.png"))); // NOI18N

        javax.swing.GroupLayout ProductsBtnLayout = new javax.swing.GroupLayout(ProductsBtn);
        ProductsBtn.setLayout(ProductsBtnLayout);
        ProductsBtnLayout.setHorizontalGroup(
            ProductsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ProductsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProductsBtnLayout.setVerticalGroup(
            ProductsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsBtnLayout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(ProductsBtn);

        AddProductsBtn.setBackground(new java.awt.Color(255, 255, 255));
        AddProductsBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        AddProductsBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        AddProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductsBtnMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Add Products");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_products.png"))); // NOI18N

        javax.swing.GroupLayout AddProductsBtnLayout = new javax.swing.GroupLayout(AddProductsBtn);
        AddProductsBtn.setLayout(AddProductsBtnLayout);
        AddProductsBtnLayout.setHorizontalGroup(
            AddProductsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddProductsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddProductsBtnLayout.setVerticalGroup(
            AddProductsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductsBtnLayout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(AddProductsBtn);

        CreateGrnBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateGrnBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        CreateGrnBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        CreateGrnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateGrnBtnMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Create GRN");

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create_grn.png"))); // NOI18N

        javax.swing.GroupLayout CreateGrnBtnLayout = new javax.swing.GroupLayout(CreateGrnBtn);
        CreateGrnBtn.setLayout(CreateGrnBtnLayout);
        CreateGrnBtnLayout.setHorizontalGroup(
            CreateGrnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CreateGrnBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        CreateGrnBtnLayout.setVerticalGroup(
            CreateGrnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateGrnBtnLayout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(CreateGrnBtn);

        ViewGrnBtn.setBackground(new java.awt.Color(255, 255, 255));
        ViewGrnBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        ViewGrnBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        ViewGrnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewGrnBtnMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("View GRN");

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list_icon.png"))); // NOI18N

        javax.swing.GroupLayout ViewGrnBtnLayout = new javax.swing.GroupLayout(ViewGrnBtn);
        ViewGrnBtn.setLayout(ViewGrnBtnLayout);
        ViewGrnBtnLayout.setHorizontalGroup(
            ViewGrnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewGrnBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ViewGrnBtnLayout.setVerticalGroup(
            ViewGrnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGrnBtnLayout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(ViewGrnBtn);

        SearchProductBtn.setBackground(new java.awt.Color(255, 255, 255));
        SearchProductBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        SearchProductBtn.setPreferredSize(new java.awt.Dimension(223, 161));
        SearchProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchProductBtnMouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Search Products");

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_item.png"))); // NOI18N

        javax.swing.GroupLayout SearchProductBtnLayout = new javax.swing.GroupLayout(SearchProductBtn);
        SearchProductBtn.setLayout(SearchProductBtnLayout);
        SearchProductBtnLayout.setHorizontalGroup(
            SearchProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addGroup(SearchProductBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchProductBtnLayout.setVerticalGroup(
            SearchProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchProductBtnLayout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stock_nav_view.add(SearchProductBtn);

        StockPageChangeArea.add(stock_nav_view, "card2");
        StockPageChangeArea.add(stockView1, "card3");
        StockPageChangeArea.add(stockGRNList1, "card9");
        StockPageChangeArea.add(stockProducts1, "card4");
        StockPageChangeArea.add(stockAddProduct1, "card5");
        StockPageChangeArea.add(stockSearch1, "card6");
        StockPageChangeArea.add(stockCreateGRN1, "card7");
        StockPageChangeArea.add(stockGRNInvoiceCreate1, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StockPageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StockPageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewStockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStockBtnMouseClicked
        stockView1.loadData();
        Home.showPanel(stockView1);
    }//GEN-LAST:event_ViewStockBtnMouseClicked

    private void ProductsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsBtnMouseClicked
        StockProducts.loadData();
        Home.showPanel(stockProducts1);
    }//GEN-LAST:event_ProductsBtnMouseClicked

    private void AddProductsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductsBtnMouseClicked
        Home.showPanel(stockAddProduct1);
    }//GEN-LAST:event_AddProductsBtnMouseClicked

    private void CreateGrnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateGrnBtnMouseClicked

        loadGRNData();

    }//GEN-LAST:event_CreateGrnBtnMouseClicked

    private void ViewGrnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewGrnBtnMouseClicked
        stockGRNList1.loadData();
        Home.showPanel(stockGRNList1);
    }//GEN-LAST:event_ViewGrnBtnMouseClicked

    private void SearchProductBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchProductBtnMouseClicked
        Home.showPanel(stockSearch1);
    }//GEN-LAST:event_SearchProductBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProductsBtn;
    private javax.swing.JPanel CreateGrnBtn;
    private javax.swing.JPanel ProductsBtn;
    private javax.swing.JPanel SearchProductBtn;
    public static javax.swing.JPanel StockPageChangeArea;
    private javax.swing.JPanel ViewGrnBtn;
    private javax.swing.JPanel ViewStockBtn;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private Pages.StockAddProduct stockAddProduct1;
    private Pages.StockCreateGRN stockCreateGRN1;
    private Pages.StockGRNInvoiceCreate stockGRNInvoiceCreate1;
    private Pages.StockGRNList stockGRNList1;
    private Pages.StockProducts stockProducts1;
    private Pages.StockSearch stockSearch1;
    private Pages.StockView stockView1;
    private javax.swing.JPanel stock_nav_view;
    // End of variables declaration//GEN-END:variables
}
