/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pages;

import smartretailer.Home;
import javax.swing.JPanel;

/**
 *
 * @author Oshan
 */
public class SupplierNav extends javax.swing.JPanel {

    /**
     * Creates new form SupplierNav
     */
    public SupplierNav() {
        initComponents();

        suplier_nav_view.setVisible(true);
    }

    public static void showPanel(JPanel panel){

        SupplierPageChangeArea.removeAll();
        SupplierPageChangeArea.add(panel);
        panel.setVisible(true);
        SupplierPageChangeArea.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierPageChangeArea = new javax.swing.JPanel();
        suplier_nav_view = new javax.swing.JPanel();
        CreateInvoiceBtn = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        InvoiceHistoryBtn = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        supplierList1 = new Pages.SupplierList();
        supplierRegister1 = new Pages.SupplierRegister();

        setPreferredSize(new java.awt.Dimension(1162, 810));

        SupplierPageChangeArea.setLayout(new java.awt.CardLayout());

        suplier_nav_view.setBackground(new java.awt.Color(255, 255, 255));

        CreateInvoiceBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateInvoiceBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        CreateInvoiceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateInvoiceBtnMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("New Supplier");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_supplier.png"))); // NOI18N

        javax.swing.GroupLayout CreateInvoiceBtnLayout = new javax.swing.GroupLayout(CreateInvoiceBtn);
        CreateInvoiceBtn.setLayout(CreateInvoiceBtnLayout);
        CreateInvoiceBtnLayout.setHorizontalGroup(
            CreateInvoiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addGroup(CreateInvoiceBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CreateInvoiceBtnLayout.setVerticalGroup(
            CreateInvoiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateInvoiceBtnLayout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        suplier_nav_view.add(CreateInvoiceBtn);

        InvoiceHistoryBtn.setBackground(new java.awt.Color(255, 255, 255));
        InvoiceHistoryBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 87, 120)));
        InvoiceHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InvoiceHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceHistoryBtnMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Supplier List");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/suplier_list.png"))); // NOI18N

        javax.swing.GroupLayout InvoiceHistoryBtnLayout = new javax.swing.GroupLayout(InvoiceHistoryBtn);
        InvoiceHistoryBtn.setLayout(InvoiceHistoryBtnLayout);
        InvoiceHistoryBtnLayout.setHorizontalGroup(
            InvoiceHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InvoiceHistoryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        InvoiceHistoryBtnLayout.setVerticalGroup(
            InvoiceHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoiceHistoryBtnLayout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        suplier_nav_view.add(InvoiceHistoryBtn);

        SupplierPageChangeArea.add(suplier_nav_view, "card2");
        SupplierPageChangeArea.add(supplierList1, "card3");
        SupplierPageChangeArea.add(supplierRegister1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplierPageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplierPageChangeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateInvoiceBtnMouseClicked
        Home.showPanel(supplierRegister1);
    }//GEN-LAST:event_CreateInvoiceBtnMouseClicked

    private void InvoiceHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceHistoryBtnMouseClicked
        supplierList1.loadData();
        Home.showPanel(supplierList1);
    }//GEN-LAST:event_InvoiceHistoryBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateInvoiceBtn;
    private javax.swing.JPanel InvoiceHistoryBtn;
    public static javax.swing.JPanel SupplierPageChangeArea;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel suplier_nav_view;
    private Pages.SupplierList supplierList1;
    private Pages.SupplierRegister supplierRegister1;
    // End of variables declaration//GEN-END:variables
}
